services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - auth-db
      - raw-materials-db
      - products-db

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  auth-service:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: auth-service
    environment:
      DATABASE_URL: ${AUTH_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      RUST_LOG: ${AUTH_RUST_LOG}
      PORT: ${AUTH_PORT}
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    depends_on:
      auth-db:
        condition: service_healthy

  raw-materials-db:
    image: postgres:15
    container_name: raw-materials-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: raw_materials_db
    ports:
      - "5433:5432"
    volumes:
      - raw_materials_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d raw_materials_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  raw-materials-service:
    build:
      context: .
      dockerfile: services/raw-materials/Dockerfile
    container_name: raw-materials-service
    environment:
      DATABASE_URL: ${RAW_MATERIALS_DATABASE_URL}
      RUST_LOG: ${RAW_MATERIALS_RUST_LOG}
      PORT: ${RAW_MATERIALS_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - ${RAW_MATERIALS_PORT}:${RAW_MATERIALS_PORT}
    depends_on:
      raw-materials-db:
        condition: service_healthy

  products-db:
    image: postgres:15
    container_name: products-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: products_db
    ports:
      - "5434:5432"
    volumes:
      - products_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d products_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  products-service:
    build:
      context: .
      dockerfile: services/products/Dockerfile
    container_name: products-service
    environment:
      DATABASE_URL: ${PRODUCTS_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      RUST_LOG: ${PRODUCTS_RUST_LOG}
      PORT: ${PRODUCTS_PORT}
    ports:
      - ${PRODUCTS_PORT}:${PRODUCTS_PORT}
    depends_on:
      products-db:
        condition: service_healthy

  productions-db:
    image: postgres:15
    container_name: productions-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: productions_db
    ports:
      - "5435:5432"
    volumes:
      - productions_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d productions_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  productions-service:
    build:
      context: .
      dockerfile: services/productions/Dockerfile
    container_name: productions-service
    environment:
      DATABASE_URL: ${PRODUCTIONS_DATABASE_URL}
      RUST_LOG: ${PRODUCTIONS_RUST_LOG}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PRODUCTIONS_PORT}
    ports:
      - ${PRODUCTIONS_PORT}:${PRODUCTIONS_PORT}
    depends_on:
      productions-db:
        condition: service_healthy

  orders-db:
    image: postgres:15
    container_name: orders-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: orders_db
    ports:
      - "5436:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d orders_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  orders-service:
    build:
      context: .
      dockerfile: services/orders/Dockerfile
    container_name: orders-service
    environment:
      DATABASE_URL: ${ORDERS_DATABASE_URL}
      RUST_LOG: ${ORDERS_RUST_LOG}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${ORDERS_PORT}
    ports:
      - ${ORDERS_PORT}:${ORDERS_PORT}
    depends_on:
      orders-db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - raw-materials-service
      - productions-service
      - products-service
      - orders-service
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=${NODE_ENV}

volumes:
  auth_db_data:
  raw_materials_db_data:
  products_db_data:
  productions_db_data:
  orders_db_data:
