events {
    worker_connections 1024;
}

http {
    upstream auth           { server auth-service:3001; }
    upstream raw_materials  { server raw-materials-service:3002; }
    upstream production     { server productions-service:3003; }
    upstream product        { server products-service:3004; }
    upstream orders         { server orders-service:3005; }
    upstream frontend       { server frontend:4200; }

    server {
        listen 80;

        location /api/auth/         { proxy_pass http://auth/;          }
        location /api/materials/    { proxy_pass http://raw_materials/;  }
        location /api/production/   { proxy_pass http://production/;     }
        location /api/products/     { proxy_pass http://product/;        }
        location /api/orders/       { proxy_pass http://orders/;         }

        # Health checks ]
        location /health/auth        { proxy_pass http://auth/health;           }
        location /health/materials   { proxy_pass http://raw_materials/health;  }
        location /health/production  { proxy_pass http://production/health;     }
        location /health/products    { proxy_pass http://product/health;        }
        location /health/orders      { proxy_pass http://orders/health;         }

        # Frontend
        location / {
            proxy_pass         http://frontend;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
            proxy_set_header   Host $host;
        }
    }
}
